### ISSUE TITLE
AsyncAPI specification 2.2.0 support

### ISSUE THREAD

**Issue by ysomad** [WaleedAshraf/asyncapi-github-action#14]
Please add support for 2.2.0.

GH actions logs:
```sh
Run WaleedAshraf/asyncapi-github-action@v0.0.4
schema file full path:/home/runner/work/anytypers/anytypers/backend/docs/asyncapi.yml
Error: AsyncAPI version is missing or unsupported: 2.2.0.
```

My GH actions configuration:
```yml
name: AsyncAPI documents processing

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      
    - name: Validating AsyncAPI document
      uses: WaleedAshraf/asyncapi-github-action@v0.0.4
      with:
        filepath: backend/docs/asyncapi.yml

```
